### ISSUE TITLE
Unknown error in IIASA query

### ISSUE THREAD

**Issue by gidden** [IAMconsortium/pyam#395]
Hi folks,

when running 
```
pyam.read_iiasa('IXSE_SR15',model='IMAGE*', variable='Secondary Energy|Electricity')
INFO:root:You are connected to the IXSE_SR15 scenario explorer hosted by IIASA. If you use this data in any published format, please cite the data as provided in the explorer guidelines: https://data.ene.iiasa.ac.at/iamc-1.5c-explorer/#/about.
```

we see 
```
RuntimeError: Trouble with request: Unrecognized field "times" (class at.ac.iiasa.ixmp.rest.v2_1.RunsResource$BulkSearchFilters), not marked as ignorable (6 known properties: "years", "variables", "runs", "timeslices", "regions", "units"])
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 427] (through reference chain: at.ac.iiasa.ixmp.rest.v2_1.RunsResource$BulkSearchParams["filters"]->at.ac.iiasa.ixmp.rest.v2_1.RunsResource$BulkSearchFilters["times"])
```

is it possible the rest API has been updated and we need to reflect that here?

@danielhuppmann @zikolach @gaurav-ganti

**Comment by danielhuppmann** [comment]
@gidden, yes there was a minor hiccup recently, but this should be fixed in the latest pyam release. And we’re devising a strategy to avoid such issues in the future.

**Comment by gidden** [comment]
@gaurav-ganti can you confirm your pyam version and the error, perhaps from the command line like:

```
$ python -c 'import pyam; print(pyam.__version__)
$ python -c "import pyam; pyam.read_iiasa('IXSE_SR15',model='IMAGE*', variable='Secondary Energy|Electricity')"
```

and report back if you're on `0.6.0` and still see the error?

**Comment by danielhuppmann** [comment]
@gaurav-ganti can you confirm that this issue does not occur any more with the latest release?

**Comment by danielhuppmann** [comment]
closing as (probably) fixed in the latest release, please reopen if the problem persists or resurfaces
